CREATE TABLE Отели (
Id_отеля INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Название_отеля nvarchar(255),
Звезды int,
Мест int,
Адрес nvarchar(255),
Парковка int,
Трансфер nvarchar(255),
Id_типа_питания INT FOREIGN KEY REFERENCES Тип_питания(Id_типа_питания)
);

INSERT INTO Отели VALUES ('"Домино"', '4', '200', 'г. Москва, ул. Кувырина, д2', '69', 'нет', '1')
INSERT INTO Отели VALUES ('"Eleon"', '2', '644', 'Московская обл, г. Королёв, ул Строителей, д55', '330', 'да', '2')
INSERT INTO Отели VALUES ('Амиго', '5', '110', 'г. Куйбышев,ул. Лесная, дом 89, кв 3', '0', 'нет', '3')
INSERT INTO Отели VALUES ('Excel winner', '1', '500', 'New-york, st. Stupid, house 22', '300', 'да', '4')
INSERT INTO Отели VALUES ('сто одна ночь у Петровича', '5', '660', '19 Avenue de la paix 1202 Geneva Switzerland', '0', 'да', '5')
INSERT INTO Отели VALUES ('Mandapa, a Ritz-Carlton Reserve', '5', '3333', 'Jl. Kedewatan, Banjar Kedewatan | Gianyar, Bali, Убуд 80571, Индонезия', '8888', 'да', '6')
INSERT INTO Отели VALUES ('Viroths Hotel', '4', '4432', '24 Street | Wat Bo Village, Сием Рип 17252, Камбоджа', '0', 'да', '7')
INSERT INTO Отели VALUES ('Tulemar Bungalows & Villas', '1', '2032', 'Tulemar Gardens, Национальный парк Мануэль Антонио 6350, Коста-Рика', '0', 'да', '8')
INSERT INTO Отели VALUES ('Тулемар Бунгало & Виллас', '5', '443', 'Tulemar Gardens, Национальный парк Мануэль Антонио 6352, Коста-Рика', '0', 'нет', '9')
INSERT INTO Отели VALUES ('Umaid Bhawan Palace Jodhpur', '3', '2212', 'Near Circuit House, Джодхпур 342006, Индия', '1', 'да', '10')
INSERT INTO Отели VALUES ('Atlantis, The Palm', '4', '1537', 'Palm Jumeirah', '2', 'нет', '11')
INSERT INTO Отели VALUES ('Al Bustan Rotana Hotel', '4', '644', 'Al Garhoud', '3', 'да', '12')
INSERT INTO Отели VALUES ('Al Maha Desert Resort', '4', '110', 'Al Ain Road', '69', 'да', '13')
INSERT INTO Отели VALUES ('Burj Al Arab', '4', '500', 'Jumeirah Beach Road', '330', 'да', '14')
INSERT INTO Отели VALUES ('Al Qasr Madinat Resort Jumeirah', '4', '1000', 'Madinat Jumeirah', '0', 'да', '15')
INSERT INTO Отели VALUES ('Bab Al Shams Desert Resort & Spa', '4', '660', 'Jumeirah', '300', 'нет', '16')
INSERT INTO Отели VALUES ('City Season Hotel', '4', '3333', 'Saeed Street', '0', 'да', '17')
INSERT INTO Отели VALUES ('Concorde Hotel & Residence', '4', '4332', 'Al Maktoum Road, Deira', '0', 'нет', '18')
INSERT INTO Отели VALUES ('Coral Boutique Hotel', '2', '2032', 'Sheikh Zayed Road', '8888', 'да', '19')
INSERT INTO Отели VALUES ('Coral Boutique Villa', '5', '443', 'Al Barsha', '0', 'нет', '20')
INSERT INTO Отели VALUES ('Dar Al Masyaf Hotel', '1', '2212', 'Madinat Jumeirah', '0', 'да', '21')
INSERT INTO Отели VALUES ('Desert Palm Dubai', '4', '26', 'Al Awir Road', '0', 'да', '22')
INSERT INTO Отели VALUES ('Dusit Dubai', '5', '174', 'Sheikh Zayed Road', '1', 'да', '23')
INSERT INTO Отели VALUES ('Habtoor Grand Resort & Spa', '5', '261', 'Al Sufoud Road', '15', 'да', '24')
INSERT INTO Отели VALUES ('The Harbour Hotel & Residence', '4', '232', 'Al Sufoud Road', '16', 'нет', '25')
INSERT INTO Отели VALUES ('Grand Hyatt Dubai', '1', '644', 'Deira Corniche', '69', 'да', '26')
INSERT INTO Отели VALUES ('Jumeirah Beach Hotel', '5', '110', 'Jumeirah', '330', 'да', '27')
INSERT INTO Отели VALUES ('Le Meridien Hotel', '3', '500', 'Airport Road', '0', 'да', '28')
INSERT INTO Отели VALUES ('Le Royal Meridien Beach Resort & Spa', '4', '1000', 'Al Sufouh', '300', 'нет', '29')
INSERT INTO Отели VALUES ('Landmark Hotel Baniyas', '4', '665', 'Baniyas', '0', 'да', '30')
INSERT INTO Отели VALUES ('Landmark Plaza Baniyas', '4', '3333', 'Baniyas', '0', 'нет', '31')
INSERT INTO Отели VALUES ('Landmark Grand Hotel', '4', '654', 'Al-Riqqa', '8888', 'да', '32')
INSERT INTO Отели VALUES ('Landmark Riqqa', '2', '2032', 'Al-Riqqa', '0', 'нет', '33')
INSERT INTO Отели VALUES ('Ramada Deira', '5', '564', 'Salah Al-Din, Deira.', '0', 'да', '34')
INSERT INTO Отели VALUES ('Madinat Mina ASalam', '1', '21', 'Jumeirah Road, Jumeirah Beach', '0', 'да', '35')
INSERT INTO Отели VALUES ('Marine Beach Resort & Spa', '4', '195', 'Jumeirah Beach Road', '0', 'да', '36')
INSERT INTO Отели VALUES ('Metropolitan Hotel', '5', '212', 'Al Maktoum Street Deira', '28', 'да', '37')
INSERT INTO Отели VALUES ('Grand Millennium Dubai', '5', '644', 'Sheikh Zayed Road', '69', 'нет', '38')
INSERT INTO Отели VALUES ('Millennium Plaza Hotel', '4', '110', 'Sheikh Zayed Road', '330', 'да', '39')
INSERT INTO Отели VALUES ('Radisson Blu Hotel Dubai', '1', '321', 'Deira', '0', 'да', '40')
INSERT INTO Отели VALUES ('Raffles Hotel', '5', '32', 'Sheikh Rashid Road', '0', 'да', '41')
INSERT INTO Отели VALUES ('Ritz Carlton Hotel', '3', '132', 'Jumeirah', '0', 'нет', '42')
INSERT INTO Отели VALUES ('Shangri-La Hotel', '4', '3333', 'Sheikh Zayed Road', '0', 'нет', '43')
INSERT INTO Отели VALUES ('Sheraton Deira Hotel', '2', '456', 'Al Muteena Street', '8888', 'нет', '44')
INSERT INTO Отели VALUES ('Sheraton Dubai Creek Hotel & Towers', '5', '2032', 'Deira', '0', 'нет', '45')
INSERT INTO Отели VALUES ('Sheraton Jumeirah Beach Resort & Towers', '1', '65', 'Al Sufouh Road', '0', 'да', '46')
INSERT INTO Отели VALUES ('Somerset Jadaf', '4', '65', 'Near Al Wasl hospital', '0', 'нет', '47')
INSERT INTO Отели VALUES ('InterContinental Dubai Festival City', '5', '619', 'Dubai Festival City', '1', 'да', '48')
INSERT INTO Отели VALUES ('Taj Palace Hotel Dubai', '5', '159', 'Deira, Dubai', '40', 'нет', '49')
INSERT INTO Отели VALUES ('JW Marriott Hotel Dubai', '4', '644', 'Abu Baker Al Siddique Road', '41', 'да', '50')
INSERT INTO Отели VALUES ('Renaissance Hotel', '1', '110', 'Deira, Dubai', '42', 'да', '51')
INSERT INTO Отели VALUES ('Jumeirah Emirates Towers Hotel', '5', '56', 'Sheikh Zayed Road', '43', 'да', '52')
INSERT INTO Отели VALUES ('Grosveнетr House West Marina Beach Dubai', '3', '6', 'Dubai Marina', '69', 'да', '53')
INSERT INTO Отели VALUES ('Park Hyatt Dubai', '4', '65', 'Al Qutaeyat Road', '330', 'нет', '54')
INSERT INTO Отели VALUES ('Mina A Salam Madinat Jumeirah', '4', '6', 'Jumeirah Road', '0', 'да', '55')
INSERT INTO Отели VALUES ('Al Qasr at Madinat', '4', '546', 'Al Sufoud Road', '300', 'нет', '56')
INSERT INTO Отели VALUES ('Kempinski Hotel Mall of the Emirates', '2', '2032', 'Sheikh Zayed Road', '0', 'да', '57')
INSERT INTO Отели VALUES ('One & Only Arabian Court at Royal Mirage', '5', '8', 'Jumeirah Beach Road', '0', 'да', '58')
INSERT INTO Отели VALUES ('One&Only Residence & Spa at Royal Mirage', '1', '54', 'Jumeirah Beach Road', '32', 'да', '59')
INSERT INTO Отели VALUES ('The Palace The Old Town', '4', '242', 'Old Town Island', '0', 'нет', '60')
INSERT INTO Отели VALUES ('Al Murooj Rotana Dubai', '5', '247', 'Al Saffa St, Sheikh Zayed Road', '32', 'да', '61')
INSERT INTO Отели VALUES ('The Monarch Dubai', '5', '234', 'Sheikh Zayed Road', '23', 'нет', '62')
INSERT INTO Отели VALUES ('Metropolitan Dubai Hotel', '4', '324', 'Sheikh Zayed Road', '1', 'да', '63')
INSERT INTO Отели VALUES ('Mina A Salam Beach Hotel Dubai', '1', '644', 'Jumeirah Beach', '55', 'нет', '64')
INSERT INTO Отели VALUES ('Sofitel - Dubai Jumeirah Beach', '5', '110', 'Jumeirah, Dubai Marina, Jumeirah Beach Residence', '56', 'да', '65')
INSERT INTO Отели VALUES ('The World Trade Centre Hotel Dubai', '3', '89', 'World Trade Center Road', '57', 'да', '66')
INSERT INTO Отели VALUES ('Hyatt Regency Dubai', '4', '564', 'Al Khaleej Road', '58', 'да', '67')
INSERT INTO Отели VALUES ('Jebel Ali Hotel & Golf Resort Dubai', '4', '6546', 'Jebel Ali Free Zone', '69', 'да', '68')
INSERT INTO Отели VALUES ('Le Meridien Mina Seyahi Resort Dubai', '4', '3333', 'Jumeirah Beach', '330', 'нет', '69')
INSERT INTO Отели VALUES ('Al Bustan Centre Residence Dubai', '2', '486', 'Al Quasis Road, Deira', '322', 'да', '70')
INSERT INTO Отели VALUES ('Beit Al Bahar Beach Villas Dubai', '5', '2032', 'Jumeirah Beach Road', '321', 'да', '71')
INSERT INTO Отели VALUES ('Crowne Plaza Hotel Dubai', '1', '65', 'Sheikh Zayed Road', '0', 'нет', '72')
INSERT INTO Отели VALUES ('Dubai Marine Beach Resort & Spa Dubai', '4', '654', 'Jumeirah Beach Road', '0', 'нет', '73')
INSERT INTO Отели VALUES ('Le Meridien Residence Dubai', '5', '65', 'Deira, Dubai', '65', 'нет', '74')
INSERT INTO Отели VALUES ('Radisson Royal Hotel', '5', '65', 'Sheikh Zayed Road,', '32', 'нет', '75')
INSERT INTO Отели VALUES ('Coral Deira Hotel', '4', '234', 'Deira, Dubai', '12', 'нет', '76')
INSERT INTO Отели VALUES ('Al Sondos Suites', '1', '432', 'Deira, Dubai', '10', 'нет', '77')
INSERT INTO Отели VALUES ('Samaya Hotel', '5', '644', 'Deira, Dubai', '1', 'да', '78')
INSERT INTO Отели VALUES ('M?venpick Hotel', '3', '110', 'Bur Dubai', '70', 'нет', '79')
INSERT INTO Отели VALUES ('Al Murooj Rotana Hotel and Suites', '4', '654', 'Sheikh Zayed Road', '71', 'да', '80')
INSERT INTO Отели VALUES ('Hilton Dubai Jumeirah Resort', '4', '542', 'Jumeirah Beach', '72', 'нет', '81')
INSERT INTO Отели VALUES ('Hilton Dubai Creek Hotel', '4', '321', 'Dubai Creek', '73', 'да', '82')
INSERT INTO Отели VALUES ('JAL hotel tower', '2', '3333', 'Sheikh Zayed Road', '69', 'да', '83')
INSERT INTO Отели VALUES ('Crowne Plaza Dubai Festival City', '2', '56', 'Dubai Festival City', '330', 'да', '84')
INSERT INTO Отели VALUES ('Gold Swiss hotel, Dubai', '5', '2315', 'Meena Road, Bur Dubai', '0', 'да', '85')
INSERT INTO Отели VALUES ('Royal Amwaj Resort and Spa', '1', '231', 'Palm Jumeirah', '300', 'нет', '86')
INSERT INTO Отели VALUES ('Ibis Al Barsha Hotel Dubai', '4', '321', 'Sheikh Zayed Road', '0', 'да', '87')
INSERT INTO Отели VALUES ('Arabian Park Hotel', '5', '234', 'Al Wasl District', '0', 'нет', '88')
INSERT INTO Отели VALUES ('Ottoman Palace Hotel and resort', '5', '448', 'Palm Jumeirah', '345', 'да', '89')
INSERT INTO Отели VALUES ('Dhow Palace (Dubai)', '4', '252', 'Mankhool road, Bur Dubai', '0', 'нет', '90')
INSERT INTO Отели VALUES ('Majestic Hotel (Dubai)', '1', '234', 'Bur Dubai', '0', 'да', '91')
INSERT INTO Отели VALUES ('Cassells Al Barsha Hotel', '5', '644', 'Al Barsha', '0', 'нет', '92')
INSERT INTO Отели VALUES ('Gloria Hotel', '3', '110', 'Sheikh Zayed Road', '1', 'да', '93')
INSERT INTO Отели VALUES ('JW Marriott Marquis Dubai Tower 1', '4', '65', 'Business Bay', '85', 'да', '94')
INSERT INTO Отели VALUES ('JW Marriott Marquis Dubai Tower 2', '4', '65', 'Business Bay', '86', 'да', '95')
INSERT INTO Отели VALUES ('Holiday Inn Dubai Al Barsha', '4', '65', 'Sheikh Zayed Road', '87', 'да', '96')
INSERT INTO Отели VALUES ('Armani Hotel Dubai', '2', '23', 'Downtown Dubai', '88', 'нет', '97')
INSERT INTO Отели VALUES ('The Fairmont Palm Hotel & Resort', '5', '32', 'Palm Jumeirah', '89', 'да', '98')
INSERT INTO Отели VALUES ('Astoria Hotel', '1', '41', 'Al Fahidi St.', '90', 'да', '99')
INSERT INTO Отели VALUES ('Ambassador Hotel', '4', '654', 'Al Fahidi St.', '400', 'нет', '100')


