CREATE TABLE Страны (
Id_страны int PRIMARY KEY IDENTITY(1,1) NOT NULL,
Наименование_страны nvarchar(255)
);

INSERT INTO Страны VALUES ('Россия')
INSERT INTO Страны VALUES ('РФ')
INSERT INTO Страны VALUES ('Russia')
INSERT INTO Страны VALUES ('United States')
INSERT INTO Страны VALUES ('Switzerland')
INSERT INTO Страны VALUES ('Индонезия')
INSERT INTO Страны VALUES ('Камбоджа')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Россия')
INSERT INTO Страны VALUES ('РФ')
INSERT INTO Страны VALUES ('Russia')
INSERT INTO Страны VALUES ('United States')
INSERT INTO Страны VALUES ('Африка')
INSERT INTO Страны VALUES ('Switzerland')
INSERT INTO Страны VALUES ('Индонезия')
INSERT INTO Страны VALUES ('Камбоджа')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Россия')
INSERT INTO Страны VALUES ('РФ')
INSERT INTO Страны VALUES ('Russia')
INSERT INTO Страны VALUES ('United States')
INSERT INTO Страны VALUES ('Африка')
INSERT INTO Страны VALUES ('Switzerland')
INSERT INTO Страны VALUES ('Индонезия')
INSERT INTO Страны VALUES ('Камбоджа')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Россия')
INSERT INTO Страны VALUES ('РФ')
INSERT INTO Страны VALUES ('Russia')
INSERT INTO Страны VALUES ('United States')
INSERT INTO Страны VALUES ('Африка')
INSERT INTO Страны VALUES ('Switzerland')
INSERT INTO Страны VALUES ('Индонезия')
INSERT INTO Страны VALUES ('Камбоджа')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Россия')
INSERT INTO Страны VALUES ('РФ')
INSERT INTO Страны VALUES ('Russia')
INSERT INTO Страны VALUES ('United States')
INSERT INTO Страны VALUES ('Африка')
INSERT INTO Страны VALUES ('Switzerland')
INSERT INTO Страны VALUES ('Индонезия')
INSERT INTO Страны VALUES ('Камбоджа')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Россия')
INSERT INTO Страны VALUES ('РФ')
INSERT INTO Страны VALUES ('Russia')
INSERT INTO Страны VALUES ('United States')
INSERT INTO Страны VALUES ('Африка')
INSERT INTO Страны VALUES ('Switzerland')
INSERT INTO Страны VALUES ('Индонезия')
INSERT INTO Страны VALUES ('Камбоджа')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Россия')
INSERT INTO Страны VALUES ('РФ')
INSERT INTO Страны VALUES ('Russia')
INSERT INTO Страны VALUES ('United States')
INSERT INTO Страны VALUES ('Африка')
INSERT INTO Страны VALUES ('Switzerland')
INSERT INTO Страны VALUES ('Индонезия')
INSERT INTO Страны VALUES ('Камбоджа')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Индия')
INSERT INTO Страны VALUES ('Россия')
INSERT INTO Страны VALUES ('РФ')
INSERT INTO Страны VALUES ('Russia')
INSERT INTO Страны VALUES ('United States')
INSERT INTO Страны VALUES ('Африка')
INSERT INTO Страны VALUES ('Switzerland')
INSERT INTO Страны VALUES ('Индонезия')
INSERT INTO Страны VALUES ('Камбоджа')
INSERT INTO Страны VALUES ('Costa-Rika')
INSERT INTO Страны VALUES ('Costa-Rika')
