CREATE TABLE Тип_питания (
Id_типа_питания INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Наименование_типа_питания nvarchar(255)
);

INSERT INTO Тип_питания VALUES ('Room Rate')
INSERT INTO Тип_питания VALUES ('All inclusive')
INSERT INTO Тип_питания VALUES ('HB+')
INSERT INTO Тип_питания VALUES ('Ultra All inclusive')
INSERT INTO Тип_питания VALUES ('Room Only')
INSERT INTO Тип_питания VALUES ('BB')
INSERT INTO Тип_питания VALUES ('full broad')
INSERT INTO Тип_питания VALUES ('FB+')
INSERT INTO Тип_питания VALUES ('BBRO')
INSERT INTO Тип_питания VALUES ('HB')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('HB')
INSERT INTO Тип_питания VALUES ('FB+')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('All inclusive')
INSERT INTO Тип_питания VALUES ('BB')
INSERT INTO Тип_питания VALUES ('bed breakfast')
INSERT INTO Тип_питания VALUES ('Ultra All inclusive')
INSERT INTO Тип_питания VALUES ('UAI')
INSERT INTO Тип_питания VALUES ('RO')
INSERT INTO Тип_питания VALUES ('BB')
INSERT INTO Тип_питания VALUES ('BB')
INSERT INTO Тип_питания VALUES ('Room Rate')
INSERT INTO Тип_питания VALUES ('bed breakfast')
INSERT INTO Тип_питания VALUES ('Room Rate')
INSERT INTO Тип_питания VALUES ('half broad plus')
INSERT INTO Тип_питания VALUES ('HB+')
INSERT INTO Тип_питания VALUES ('Room Only')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('half broad plus')
INSERT INTO Тип_питания VALUES ('UAI')
INSERT INTO Тип_питания VALUES ('half broad')
INSERT INTO Тип_питания VALUES ('Room Only')
INSERT INTO Тип_питания VALUES ('FB')
INSERT INTO Тип_питания VALUES ('bed breakfast')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('full broad')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('bed breakfast')
INSERT INTO Тип_питания VALUES ('AI')
INSERT INTO Тип_питания VALUES ('FB')
INSERT INTO Тип_питания VALUES ('UAI')
INSERT INTO Тип_питания VALUES ('Room Rate')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('HB+')
INSERT INTO Тип_питания VALUES ('FB+')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('HB')
INSERT INTO Тип_питания VALUES ('half broad plus')
INSERT INTO Тип_питания VALUES ('FB+')
INSERT INTO Тип_питания VALUES ('HB')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('AI')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('Room Rate')
INSERT INTO Тип_питания VALUES ('full broad')
INSERT INTO Тип_питания VALUES ('RO')
INSERT INTO Тип_питания VALUES ('half broad plus')
INSERT INTO Тип_питания VALUES ('HB')
INSERT INTO Тип_питания VALUES ('half broad')
INSERT INTO Тип_питания VALUES ('FB')
INSERT INTO Тип_питания VALUES ('HB')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('full broad')
INSERT INTO Тип_питания VALUES ('HB')
INSERT INTO Тип_питания VALUES ('FB')
INSERT INTO Тип_питания VALUES ('Ultra All inclusive')
INSERT INTO Тип_питания VALUES ('Room Only')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('Ultra All inclusive')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('UAI')
INSERT INTO Тип_питания VALUES ('FB+')
INSERT INTO Тип_питания VALUES ('Room Only')
INSERT INTO Тип_питания VALUES ('FB')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('FB+')
INSERT INTO Тип_питания VALUES ('Ultra All inclusive')
INSERT INTO Тип_питания VALUES ('Only Bed')
INSERT INTO Тип_питания VALUES ('Room Only')
INSERT INTO Тип_питания VALUES ('HB+')
INSERT INTO Тип_питания VALUES ('OB')
INSERT INTO Тип_питания VALUES ('Ultra All inclusive')
INSERT INTO Тип_питания VALUES ('All inclusive')
INSERT INTO Тип_питания VALUES ('Room Only')
INSERT INTO Тип_питания VALUES ('Room Only')
INSERT INTO Тип_питания VALUES ('Room Rate')
INSERT INTO Тип_питания VALUES ('HB+')
INSERT INTO Тип_питания VALUES ('Room Rate')
INSERT INTO Тип_питания VALUES ('HB+')
INSERT INTO Тип_питания VALUES ('half broad plus')
INSERT INTO Тип_питания VALUES ('Ultra All inclusive')
INSERT INTO Тип_питания VALUES ('bed breakfast')
INSERT INTO Тип_питания VALUES ('half broad')
INSERT INTO Тип_питания VALUES ('HB')
INSERT INTO Тип_питания VALUES ('UAI')

